name: Run Postman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      # OPTIONAL: If you use an environment file, uncomment below:
       - name: Install Newman HTML Reporter (optional)
         run: npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run github/workflows/17604848-08a6ecbd-2cc1-42b6-a387-4582297bb5f0.json \
              --environment github/workflows/New Environment.postman_environment.json \
              --reporters cli,json \
              --reporter-json-export newman-report.json

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.json
